### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by curiousercreative** [lastuniverse/path-to-regex#1]
Internet Explorer 11 currently throws an error when evaluating `path-to-regex` because it does not support [default parameters](https://kangax.github.io/compat-table/es6/#test-default_function_parameters) that are used [here](https://github.com/lastuniverse/path-to-regex/blob/master/index.js#L44) and [here](https://github.com/lastuniverse/path-to-regex/blob/master/index.js#L61).

Of course, the problem can be solved through transpiling, but it should be a simple enough patch to support IE11 without transpiling.

**Comment by lastuniverse** [comment]
I heard you. In the near future (but not earlier than in 3 weeks) I will deal with this request. At the moment I do not have the opportunity to work (moving to a new place of residence)

**Comment by lastuniverse** [comment]
Thanks for your pull request. I apologize for not paying attention for a long time.
